/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.77
 * Generated at: 2022-04-07 12:05:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/smartrash_workspace/smartrash/src/main/webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/smartrash_workspace/smartrash/src/main/webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1648709425000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Page Title -->\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<title>SmarTrash - ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ page_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\r\n");
      out.write("		");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		<style type=\"text/css\">\r\n");
      out.write("			#drop-zone {\r\n");
      out.write("			    outline: 10px dashed #fff ;\r\n");
      out.write("			    outline-offset:-10px;  \r\n");
      out.write("			    text-align: center;\r\n");
      out.write("			    width: 50%;\r\n");
      out.write("			    height: 300px;\r\n");
      out.write("			    -webkit-text-stroke-width: 0.5px;\r\n");
      out.write("			    -webkit-text-stroke-color: black;\r\n");
      out.write("			}\r\n");
      out.write("			#drop-zone.hover {\r\n");
      out.write("				border: 10px dashed #333;\r\n");
      out.write("			}\r\n");
      out.write("		</style>\r\n");
      out.write("		<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.servletContext.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("		<script type=\"text/javascript\">\r\n");
      out.write("		$(function() {\r\n");
      out.write("			$image = document.getElementById(\"upload-file-input\")\r\n");
      out.write("			dropZone = document.querySelector(\"#drop-zone\")\r\n");
      out.write("			\r\n");
      out.write("			$(dropZone)\r\n");
      out.write("				.on(\"dragover\", dragOver)\r\n");
      out.write("				.on(\"dragleave\", dragOver)\r\n");
      out.write("				.on(\"click\", ajaxFileSelect);\r\n");
      out.write("			\r\n");
      out.write("			function dragOver(e) {\r\n");
      out.write("			    e.stopPropagation();\r\n");
      out.write("			    e.preventDefault();\r\n");
      out.write("			    if (e.type == \"dragover\") {\r\n");
      out.write("			        $(e.target).css({\r\n");
      out.write("			            \"transform\": \"scale(0.9)\",\r\n");
      out.write("			            \"transition\": \"transform .25s\"\r\n");
      out.write("			        });\r\n");
      out.write("			    } else {\r\n");
      out.write("			        $(e.target).css({\r\n");
      out.write("			            \"transform\": \"scale(1.0)\",\r\n");
      out.write("			            \"transition\": \"transform .25s\"\r\n");
      out.write("			        });\r\n");
      out.write("			    }\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			/* var showFiles = function (files) {\r\n");
      out.write("				dropZone.innerHTML = \"\"\r\n");
      out.write("				for (var i = 0, len = files.length; i < len; i++) {\r\n");
      out.write("					dropZone.innerHTML += \"<p>\" + files[i].name + \"</p>\"\r\n");
      out.write("				}\r\n");
      out.write("			} */\r\n");
      out.write("			\r\n");
      out.write("			var selectFile = function (files) {\r\n");
      out.write("				// input file 영역에 드랍된 파일들로 대체\r\n");
      out.write("				$image.files = files\r\n");
      out.write("				/* showFiles($image.files) */\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			/* $image.addEventListener(\"change\", function (e) {\r\n");
      out.write("				showFiles(e.target.files)\r\n");
      out.write("			}) */\r\n");
      out.write("			\r\n");
      out.write("			// 드래그한 파일이 드랍되었을 때\r\n");
      out.write("			dropZone.addEventListener(\"drop\", function (e) {\r\n");
      out.write("				e.preventDefault()\r\n");
      out.write("		        $(e.target).css({\r\n");
      out.write("		            \"transform\": \"scale(1.0)\",\r\n");
      out.write("		            \"transition\": \"transform .25s\"\r\n");
      out.write("		        });\r\n");
      out.write("				var files = e.dataTransfer && e.dataTransfer.files\r\n");
      out.write("				console.log(files)\r\n");
      out.write("				if (files != null) {\r\n");
      out.write("					if(files[0].type.match(/image.*/)) {\r\n");
      out.write("						\r\n");
      out.write("						$(dropZone).html(\"업로드한 쓰레기사진을 분류중입니다. <br> 잠시만 기달려 주세요\");\r\n");
      out.write("					    $(dropZone).css({\r\n");
      out.write("					        \"background-image\": \"url(\" + window.URL.createObjectURL(files[0]) + \")\",\r\n");
      out.write("					        \"background-size\": \"contain\",\r\n");
      out.write("					        \"background-repeat\": \"no-repeat\",\r\n");
      out.write("					        \"background-position\": \"center\"\r\n");
      out.write("					    });\r\n");
      out.write("						\r\n");
      out.write("						selectFile(files)\r\n");
      out.write("						\r\n");
      out.write("						ajaxFileUpload()\r\n");
      out.write("					}else{\r\n");
      out.write("						alert('이미지가 아닙니다.');\r\n");
      out.write("						dropZone.innerHTML = \"Drop & Click\"\r\n");
      out.write("		        		$('#drop-zone').css({\r\n");
      out.write("					        \"background-image\": \"none\"\r\n");
      out.write("					    });\r\n");
      out.write("						return;\r\n");
      out.write("					}\r\n");
      out.write("				} else {\r\n");
      out.write("					alert(\"ERROR\")\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("			\r\n");
      out.write("			function ajaxFileSelect() {\r\n");
      out.write("		        jQuery(\"#upload-file-input\").click();\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			jQuery(document).ready(function($) {\r\n");
      out.write("			    $(\"#upload-file-input\").change(function() {\r\n");
      out.write("			        var files = !!this.files ? this.files : [];\r\n");
      out.write("			        if(!files.length || !window.FileReader) {\r\n");
      out.write("			        	dropZone.innerHTML = \"Drop & Click\"\r\n");
      out.write("		        		$(dropZone).css({\r\n");
      out.write("					        \"background-image\": \"none\"\r\n");
      out.write("					    });\r\n");
      out.write("			        	return; // no file selected, or no FileReader support\r\n");
      out.write("			        }\r\n");
      out.write("			        \r\n");
      out.write("			        if(/^image/.test( files[0].type)){ // only image file\r\n");
      out.write("				    	ajaxFileUpload()\r\n");
      out.write("			        	\r\n");
      out.write("			            var reader = new FileReader(); // instance of the FileReader\r\n");
      out.write("			            reader.readAsDataURL(files[0]); // read the local file\r\n");
      out.write("			            reader.onload = function(e) {\r\n");
      out.write("			            	\r\n");
      out.write("			    			$(dropZone).html(\"업로드한 쓰레기사진을 분류중입니다. <br> 잠시만 기달려 주세요\");\r\n");
      out.write("			            	$(dropZone).css({\r\n");
      out.write("						        \"background-image\": \"url(\" + e.target.result + \")\",\r\n");
      out.write("						        \"background-size\": \"contain\",\r\n");
      out.write("						        \"background-repeat\": \"no-repeat\",\r\n");
      out.write("						        \"background-position\": \"center\"\r\n");
      out.write("						    });\r\n");
      out.write("			            	console.log(e.target.result)\r\n");
      out.write("			            }\r\n");
      out.write("			        } else {\r\n");
      out.write("			        	alert('이미지가 아닙니다.');\r\n");
      out.write("			        	dropZone.innerHTML = \"Drop & Click\"\r\n");
      out.write("		        		$(dropZone).css({\r\n");
      out.write("					        \"background-image\": \"none\"\r\n");
      out.write("					    });\r\n");
      out.write("						return;\r\n");
      out.write("			        }\r\n");
      out.write("			        \r\n");
      out.write("			    });\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("		    function ajaxFileUpload() {\r\n");
      out.write("		    	$.ajax({\r\n");
      out.write("					url: \"uploadFile.do\",\r\n");
      out.write("					type: \"POST\",\r\n");
      out.write("					data: new FormData($(\"#upload-file-form\")[0]),\r\n");
      out.write("					dataType: \"json\",\r\n");
      out.write("					enctype: 'multipart/form-data',\r\n");
      out.write("					processData: false,\r\n");
      out.write("					contentType: false,\r\n");
      out.write("					cache: false,\r\n");
      out.write("					success: function (data) {\r\n");
      out.write("						console.log(\"success\");\r\n");
      out.write("						var jsonStr = JSON.stringify(data);\r\n");
      out.write("						var json = JSON.parse(jsonStr);\r\n");
      out.write("						\r\n");
      out.write("						var values = \"\";\r\n");
      out.write("						for(var i in json.list){  // i(인덱스) 변수가 자동으로 1씩 증가 처리됨\r\n");
      out.write("							values += \"<input type='text' name='file' value='\" + json.list[i].file + \"'  style='display:none;' />\"\r\n");
      out.write("									+ \"<input type='text' name='category' value='\" + json.list[i].category + \"'  style='display:none;' />\";\r\n");
      out.write("							console.log(\"file : \" + json.list[i].file);\r\n");
      out.write("							console.log(\"category : \" + json.list[i].category);\r\n");
      out.write("						}\r\n");
      out.write("						$(\"#data-push-form\").html($(\"#data-push-form\").html() + values);\r\n");
      out.write("						jQuery(\"#data-push-submit\").click();\r\n");
      out.write("					},\r\n");
      out.write("					error: function () {\r\n");
      out.write("						console.log(\"error\");\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("		    }\r\n");
      out.write("		});\r\n");
      out.write("		</script>\r\n");
      out.write("	</head>\r\n");
      out.write("    <body class=\"d-flex flex-column h-100\">\r\n");
      out.write("        <main class=\"flex-shrink-0\">\r\n");
      out.write("            <!-- Navigation-->\r\n");
      out.write("			");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            <!-- Header-->\r\n");
      out.write("            <header class=\"bg-dark\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row align-items-center justify-content-center\">\r\n");
      out.write("	                    <div class=\"my-2\">\r\n");
      out.write("	                        <h1 class=\"display-5 fw-bolder text-white mb-2 text-center\">SmarTrash</h1>\r\n");
      out.write("	                    </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row align-items-center justify-content-center\" align=\"center\">\r\n");
      out.write("						<div class=\"my-2\">\r\n");
      out.write("							<form id=\"upload-file-form\">\r\n");
      out.write("								<div id=drop-zone class=\"text-white d-flex align-items-center justify-content-center user-select-none\">Drop & Click</div>\r\n");
      out.write("								<input id=\"upload-file-input\" type=\"file\" name=\"uploadfile\" style=\"display:none;\" />\r\n");
      out.write("								<input type=\"submit\" id=\"upload-file-submit\" name=\"submit\" style=\"display:none;\" />\r\n");
      out.write("							</form>\r\n");
      out.write("							<form id=\"data-push-form\" action=\"dataPush.do\" method=\"post\">\r\n");
      out.write("								<input type=\"submit\" id=\"data-push-submit\" name=\"submit\" style=\"display:none;\" />\r\n");
      out.write("							</form>\r\n");
      out.write("						</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row align-items-center justify-content-center\">\r\n");
      out.write("						<div class=\"my-4 text-center\">\r\n");
      out.write("						</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </header>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Features section-->\r\n");
      out.write("			<section class=\"bg-light\">\r\n");
      out.write("                <div class=\"container px-5\">\r\n");
      out.write("                    <div class=\"text-center py-3\">\r\n");
      out.write("                        <h1 class=\"fs-4\">최근 분류된 쓰레기</h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row justify-content-center\">\r\n");
      out.write("                        <!-- Pricing card free-->\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("            </section>\r\n");
      out.write("        </main>\r\n");
      out.write("        <!-- Footer-->\r\n");
      out.write("		");
      if (_jspx_meth_c_005fimport_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/common/main.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("page_title");
      // /WEB-INF/views/common/main.jsp(7,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/common/main.jsp(7,0) '메인 페이지'",_jsp_getExpressionFactory().createValueExpression("메인 페이지",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/views/common/main.jsp(13,2) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("/WEB-INF/views/common/head.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /WEB-INF/views/common/main.jsp(188,3) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("/WEB-INF/views/common/navi.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/common/main.jsp(224,24) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/common/main.jsp(224,24) '${ requestScope.trash_list }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ requestScope.trash_list }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/common/main.jsp(224,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("t");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("							<div style=\"width:120px;\" class=\"mx-1 pb-3 justify-content-center\">\r\n");
            out.write("								<div style=\"width:96px; height:96px; background-image: url('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.servletContext.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/trash_upfiles/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ t.trash_path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("'); background-position: center; background-size: 100% 100%;\" class=\"align-items-center d-flex justify-content-center rounded-circle\">\r\n");
            out.write("									");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ status.count }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("								</div>\r\n");
            out.write("								<div class=\"pt-1 user-select-none text-center\">\r\n");
            out.write("									");
            if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("									<br>\r\n");
            out.write("									");
            if (_jspx_meth_fmt_005fformatDate_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("								</div>\r\n");
            out.write("							</div>\r\n");
            out.write("						");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/common/main.jsp(229,9) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ t.trash_date }", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/common/main.jsp(229,9) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yy-MM-dd");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/common/main.jsp(231,9) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ t.trash_date }", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/common/main.jsp(231,9) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setPattern("HH:mm:ss");
      int _jspx_eval_fmt_005fformatDate_005f1 = _jspx_th_fmt_005fformatDate_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f1);
      _jspx_th_fmt_005fformatDate_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f2 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f2_reused = false;
    try {
      _jspx_th_c_005fimport_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f2.setParent(null);
      // /WEB-INF/views/common/main.jsp(240,2) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f2.setUrl("/WEB-INF/views/common/foot.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f2 = _jspx_th_c_005fimport_005f2.doStartTag();
        if (_jspx_th_c_005fimport_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f2);
      _jspx_th_c_005fimport_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f2_reused);
    }
    return false;
  }
}
